### ISSUE TITLE
Add this awesome-auth list to the global awesome list's list

### ISSUE THREAD

**Issue by hsluoyz** [casbin/awesome-auth#19]
We need to add this awesome-auth list to the global awesome list's list: https://github.com/sindresorhus/awesome

I have tried twice before:

1. https://github.com/sindresorhus/awesome/pull/1042
2. https://github.com/sindresorhus/awesome/pull/1364

But doesn't make it to the end.

I hope someone could add this list to: https://github.com/sindresorhus/awesome via a PR.

**Comment by hsluoyz** [comment]
@tangyang9464

**Comment by tangyang9464** [comment]
@hsluoyz According to Guidelines，the default branch should be named main, not master for awesome list.Does this need to be modified?

**Comment by hsluoyz** [comment]
@tangyang9464 guideline link?

**Comment by tangyang9464** [comment]
@hsluoyz [guideline](https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md#requirements-for-your-awesome-list)
fourth point

**Comment by hsluoyz** [comment]
@tangyang9464 done

**Comment by tangyang9464** [comment]
@hsluoyz 
https://github.com/sindresorhus/awesome/pull/2033#issuecomment-867118907
It seems unable to add
