### ISSUE TITLE
ORY: Where do they fit (if at all)?

### ISSUE THREAD

**Issue by begincalendar** [casbin/awesome-auth#7]
I'm happy to make PR(s) for these, but I thought I should double check where they should go first.

_Note: I have no affiliation with ORY and am just evaluating solutions for use in a greenfield project._

# Agnostic

## [ORY Hydra](https://github.com/ory/hydra): OpenID Connect certified OAuth2 Server

OAuth2 is authorization, but OpenID Connect is authentication, so would this need a new category (e.g. Authentication/Authorization)?

## [ORY Oathkeeper](https://github.com/ory/oathkeeper): Cloud native identity and access proxy

Similar to **Hydra**, this deals with authentication and authorization.

## [ORY Keto](https://github.com/ory/keto): Access control server

This is authorisation, but agnostic (non-existent category).

# Golang

## ~[ORY Ladon](https://github.com/ory/ladon): Golang access control policy SDK~

~This can go under **Authorization - Golang**, I believe.~

## [ORY Fosite](https://github.com/ory/fosite): Golang OAuth 2.0 and OpenID Connect SDK

Golang-specific, but deals with authentication and authorization.

**Comment by hsluoyz** [comment]
I think OAuth goes to authentication better, because its authorization functionality is weak. So Hydra, Oathkeeper, Fosite go to authentication. Keto goes to authorization. Ladon is already in the list. The language also means the development language. So I think all projects go to Golang.

**Comment by begincalendar** [comment]
I'm happy to make the PRs based on what you've said, but...

I'm not sure I agree with OAuth being more about authentication than authorization.
Please refer to this [answer](https://stackoverflow.com/a/1087071/2117581) and the surrounding discussion.

Although I agree it's (unfortunately) not clear cut, I think OAuth is more about authorization (than authentication).

**Comment by hsluoyz** [comment]
I know what you mean, I even saw that StackoverFlow before. But here's question that if we move all OAuth projects from Authentication to Authorization, there's nearly nothing left in the Authentication category.

I know OAuth has authorization functionality, but it's very limited compared to other more general solutions like RBAC, ABAC.

Maybe another way is to separate based on OpenID, SAML, OAuth, General Authorization, etc.

**Comment by begincalendar** [comment]
> I know what you mean, I even saw that StackoverFlow thread before. But here's question that if we move all OAuth projects from Authentication to Authorization, there's nearly nothing left in the Authentication category.
>
>I know OAuth has authorization functionality, but it's very limited compared to other more general solutions like RBAC, ABAC.

Fair enough.

> Maybe another way is to separate based on OpenID, SAML, OAuth, General Authorization, etc.

Perhaps, but I don't want to hijack this issue with a discussion on that.

I shall make the appropriate PRs based on your [first comment](https://github.com/casbin/awesome-auth/issues/7#issuecomment-412729070).

_P.S. Thank you for creating/maintaining Casbin and this "alternatives repo"._

**Comment by begincalendar** [comment]
Refer to #10, #11, #12 and #13.

**Comment by hsluoyz** [comment]
Thanks for the PRs!
